# Generated by Django 4.0.3 on 2023-06-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wykres', '0002_no2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='no2',
            options={'ordering': ('date',)},
        ),
    ]
