# Generated by Django 4.0.3 on 2023-06-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wykres', '0003_alter_no2_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_ID', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
