# Generated by Django 4.0.3 on 2023-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wykres', '0004_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PM25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
