# Generated by Django 4.0.3 on 2023-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wykres', '0006_alter_no2_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm10',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
