# Generated by Django 4.0.3 on 2023-09-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wykres', '0007_alter_pm10_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
